# Generated by Django 4.2 on 2024-04-15 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hashtag',
            field=models.ManyToManyField(related_name='hashtag', to=settings.AUTH_USER_MODEL),
        ),
    ]
