# Generated by Django 4.2 on 2024-04-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hashtag',
        ),
    ]
